sonar.projectKey=Resume-Enhancer
sonar.projectName=Resume Enhancer
sonar.projectVersion=1.0

sonar.sources=src/main,frontend
sonar.tests=src/test

sonar.host.url=http://localhost:9000

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S2143
sonar.issue.ignore.multicriteria.e1.resourceKey=**/TokenService.java