spring.application.name=cvenchancer
spring.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
spring.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
spring.opentelemetry.metrics.export.otlp.endpoint=http://localhost:4318/v1/metrics
spring.management.tracing.sampling.probability=1.0